# Generated by Django 3.0.6 on 2020-07-29 04:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='stocks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
