# Generated by Django 3.0.6 on 2020-08-07 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cashtransactions_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransactions',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
